clear, clc, close;
syms x y;
s = solve(x^2+(y*5/4-sqrt(abs(x)))^2 == 1, y);
x = -1:0.01:1;
y = subs(s);


%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 16-Sep-2023 10:07:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot(x, y,'LineWidth',3,'Color',[1 0 0]);
fill(x, y, 'b')
% Create ylabel
ylabel('Y');

% Create xlabel
xlabel('X');

% Create title
title('x^2+(y*5/4-sqrt(abs(x)))^2 == 1','HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontAngle','italic');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color',[0.650980392156863 0.650980392156863 0.650980392156863],...
    'FontAngle','italic','XColor',[0 0 0],'XGrid','on','YColor',[0 0 0],'YGrid',...
    'on','ZColor',[0 0 0], Layer = 'top');

datetime(clock)
